version: "3"
services:
  nginx:
    build: ./docker/nginx/
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - socket-volume:/socket
    environment:
      - TZ=${TZ}
  backend:
    build: ./backend
    volumes:
      - ./backend:/home/python/app
      - socket-volume:/socket
    tty: true
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/home/node/app
    tty: true
  mysql:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
volumes:
  db-store:
  socket-volume:
