@startuml

class XmlToJson

class Feeds{
    -articles 直近n日分の全てのサイトの記事をセット
    -setArticles() articlesにRSS情報をセット
    -sort() articlesを日付降順でソート
    +get() ソートされたデータを取得 
}

class Rss{
    feeds()
}



@enduml